#!/usr/bin/env node

import {existsSync, mkdirSync, readFileSync, statSync, writeFileSync,} from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import {parquetMetadata, parquetSchema, type SchemaElement, type SchemaTree,} from 'hyparquet'
import {Project} from 'ts-morph'

const PARQUET_FILENAME = 'full_debate_analysis.parquet'
const PARQUET_SOURCE = path.resolve(process.cwd(), 'web', 'src', 'parquet', PARQUET_FILENAME)

function main(): void {
  try {
    run()
  } catch (error) {
    console.error(error)
    process.exitCode = 1
  }
}

function run(): void {
  const parquetPath = resolveParquetPath()
  if (!parquetPath) {
    console.warn(`Parquet file not found at ${PARQUET_SOURCE}`)
    return
  }

  const { filePath, schema } = loadSchema(parquetPath)
  const interfaceName = inferInterfaceName(PARQUET_FILENAME)
  const generatedType = generateTypeScriptSource({
    interfaceName,
    schema,
    parquetPath: filePath,
  })

  const outputPath = process.argv[2]
  if (outputPath) {
    const resolvedOutput = path.resolve(process.cwd(), outputPath)
    mkdirSync(path.dirname(resolvedOutput), { recursive: true })
    writeFileSync(resolvedOutput, generatedType, 'utf8')
    console.log(`TypeScript schema written to ${resolvedOutput}`)
  } else {
    process.stdout.write(generatedType)
  }

  const columnNames = schema.children.map(child => child.element.name)
  console.log(
    [
      `Columns discovered in ${path.relative(process.cwd(), filePath)}:`,
      `  ${columnNames.join(', ')}`,
    ].join('\n')
  )
}

function resolveParquetPath(): string | null {
  if (!existsSync(PARQUET_SOURCE)) {
    return null
  }
  const stats = statSync(PARQUET_SOURCE)
  if (!stats.isFile()) {
    console.warn(`Expected a file at ${PARQUET_SOURCE}, but found something else.`)
    return null
  }
  return PARQUET_SOURCE
}

function loadSchema(parquetPath: string): {
  filePath: string
  schema: SchemaTree
} {
  const filePath = parquetPath
  const buffer = readFileSync(filePath)
  const arrayBuffer = buffer.buffer.slice(
    buffer.byteOffset,
    buffer.byteOffset + buffer.byteLength
  )
  const metadata = parquetMetadata(arrayBuffer)
  const schema = parquetSchema(metadata)
  return { filePath, schema }
}

function inferInterfaceName(filename: string): string {
  const base = filename.replace(/\.parquet$/i, '')
  return `${toPascalCase(base)}Row`
}

function toPascalCase(text: string): string {
  return text
    .replace(/[_\-\s]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map(chunk => chunk.charAt(0).toUpperCase() + chunk.slice(1).replace(/[^a-zA-Z0-9]/g, ''))
    .join('')
}

function generateTypeScriptSource({
  interfaceName,
  schema,
  parquetPath,
}: {
  interfaceName: string
  schema: SchemaTree
  parquetPath: string
}): string {
  const project = new Project({ useInMemoryFileSystem: true })
  const sourceFile = project.createSourceFile('generated.ts', '', {
    overwrite: true,
  })

  sourceFile.addStatements(writer => {
    writer.writeLine(
      `// This file was auto-generated by scripts/generate-parquet-schema.mts`
    )
    writer.writeLine(
      `// Source parquet file: ${path.relative(process.cwd(), parquetPath) || parquetPath}`
    )
    writer.blankLine()
  })

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'hyparquet',
    namedImports: ['parquetReadObjects'],
  })

  sourceFile.addStatements(writer => {
    writer.blankLine()
  })

  const interfaceDeclaration = sourceFile.addInterface({
    isExported: true,
    name: interfaceName,
  })

  if (!schema.children.length) {
    interfaceDeclaration.addProperty({
      name: '[key: string]',
      type: 'unknown',
    })
  } else {
    for (const child of schema.children) {
      interfaceDeclaration.addProperty({
        name: formatPropertyName(child.element.name),
        hasQuestionToken: child.element.repetition_type !== 'REQUIRED',
        type: renderType(child, 1),
      })
    }
  }

  sourceFile.addStatements(writer => {
    writer.blankLine()
    writer.writeLine(`export interface ${interfaceName}FetchOptions {`)
    writer.writeLine(`  /** Custom fetch implementation (defaults to global fetch). */`)
    writer.writeLine(`  fetch?: typeof fetch;`)
    writer.writeLine(`  /** Additional RequestInit options passed to fetch. */`)
    writer.writeLine(`  requestInit?: RequestInit;`)
    writer.writeLine(`}`)
    writer.blankLine()
    writer.writeLine(`export async function fetch${interfaceName}s(url: string, options?: ${interfaceName}FetchOptions): Promise<${interfaceName}[]> {`)
    writer.writeLine(`  const fetchImpl = options?.fetch ?? globalThis.fetch;`)
    writer.writeLine(`  if (!fetchImpl) {`)
    writer.writeLine(`    throw new Error('fetch is not available in this environment');`)
    writer.writeLine(`  }`)
    writer.writeLine(`  const requestInit = options?.requestInit;`)
    writer.writeLine(`  const response = await fetchImpl(url, requestInit);`)
    writer.writeLine(`  if (!response.ok) {`)
    writer.writeLine(`    throw new Error(\`parquet fetch failed \${response.status}\`);`)
    writer.writeLine(`  }`)
    writer.writeLine(`  const buffer = await response.arrayBuffer();`)
    writer.writeLine(`  const file = {`)
    writer.writeLine(`    byteLength: buffer.byteLength,`)
    writer.writeLine(`    async slice(start: number, end?: number) {`)
    writer.writeLine(`      return buffer.slice(start, end);`)
    writer.writeLine(`    },`)
    writer.writeLine(`  };`)
    writer.writeLine(`  try {`)
    writer.writeLine(`    const rows = await parquetReadObjects({`)
    writer.writeLine(`      file,`)
    writer.writeLine(`      rowFormat: 'object',`)
    writer.writeLine(`    } as Parameters<typeof parquetReadObjects>[0]);`)
    writer.writeLine(`    return rows as ${interfaceName}[];`)
    writer.writeLine(`  } catch (error) {`)
    writer.writeLine(`    throw error;`)
    writer.writeLine(`  }`)
    writer.writeLine(`}`)
  })

  sourceFile.formatText({
    indentSize: 2,
    ensureNewLineAtEndOfFile: true,
  })

  return sourceFile.getFullText()
}

function renderType(node: SchemaTree, indentLevel: number): string {
  if (isAnnotatedList(node)) {
    const listNode = node.children[0]
    const itemNode = listNode?.children[0] ?? listNode
    const itemType = renderType(itemNode, indentLevel)
    return wrapArrayType(itemType)
  }

  if (isAnnotatedMap(node)) {
    const keyValueNode = node.children[0]
    const keyNode = keyValueNode?.children.find(child => child.element.name === 'key')
    const valueNode = keyValueNode?.children.find(child => child.element.name === 'value')
    const keyType = keyNode ? mapKeyType(keyNode) : 'string'
    const valueType = valueNode ? wrapComplexType(renderType(valueNode, indentLevel + 1)) : 'unknown'
    return `Record<${keyType}, ${valueType}>`
  }

  if (node.element.repetition_type === 'REPEATED') {
    const nonRepeatedNode: SchemaTree = {
      ...node,
      element: {
        ...node.element,
        repetition_type: 'REQUIRED',
      },
    }
    const itemType = renderNonRepeatedType(nonRepeatedNode, indentLevel)
    return wrapArrayType(itemType)
  }

  return renderNonRepeatedType(node, indentLevel)
}

function renderNonRepeatedType(node: SchemaTree, indentLevel: number): string {
  if (node.children.length) {
    const innerLevel = indentLevel + 1
    const indent = '  '.repeat(innerLevel)
    const closingIndent = '  '.repeat(indentLevel)
    const properties = node.children
      .map(child => {
        const propertyName = formatPropertyName(child.element.name)
        const optional = child.element.repetition_type !== 'REQUIRED' ? '?' : ''
        const typeString = renderType(child, innerLevel)
        const formattedType = indentMultiline(typeString, `${indent}  `)
        return `${indent}${propertyName}${optional}: ${formattedType};`
      })
      .join('\n')
    return `{\n${properties}\n${closingIndent}}`
  }

  return primitiveType(node.element)
}

function wrapArrayType(typeString: string): string {
  const trimmed = typeString.trim()
  if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
    return `(${typeString})[]`
  }
  if (trimmed.includes('\n')) {
    return `(${typeString})[]`
  }
  return `${typeString}[]`
}

function wrapComplexType(typeString: string): string {
  const trimmed = typeString.trim()
  if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
    return `(${typeString})`
  }
  if (trimmed.includes('\n')) {
    return `(${typeString})`
  }
  return typeString
}

function primitiveType(element: SchemaElement): string {
  const { type, converted_type: convertedType, logical_type: logicalType } = element
  if (logicalType) {
    if (logicalType.type === 'STRING') return 'string'
    if (logicalType.type === 'JSON') return 'unknown'
    if (logicalType.type === 'BSON') return 'Uint8Array'
    if (logicalType.type === 'UUID') return 'string'
    if (logicalType.type === 'DATE') return 'Date'
    if (logicalType.type === 'TIME') return 'number'
    if (logicalType.type === 'TIMESTAMP') return 'Date'
    if (logicalType.type === 'INTEGER') {
      return logicalType.bitWidth <= 32 ? 'number' : 'bigint'
    }
    if (logicalType.type === 'VARIANT') return 'unknown'
    if (logicalType.type === 'GEOMETRY' || logicalType.type === 'GEOGRAPHY') {
      return 'unknown'
    }
  }

  if (convertedType) {
    switch (convertedType) {
      case 'UTF8':
      case 'ENUM':
        return 'string'
      case 'JSON':
        return 'unknown'
      case 'BSON':
        return 'Uint8Array'
      case 'DECIMAL':
        return 'number'
      case 'DATE':
        return 'Date'
      case 'TIME_MILLIS':
      case 'TIME_MICROS':
        return 'number'
      case 'TIMESTAMP_MILLIS':
      case 'TIMESTAMP_MICROS':
        return 'Date'
      case 'UINT_8':
      case 'UINT_16':
      case 'UINT_32':
      case 'INT_8':
      case 'INT_16':
      case 'INT_32':
        return 'number'
      case 'UINT_64':
      case 'INT_64':
        return 'bigint'
      default:
        break
    }
  }

  switch (type) {
    case 'BOOLEAN':
      return 'boolean'
    case 'INT32':
      return 'number'
    case 'INT64':
      return 'bigint'
    case 'INT96':
      return 'Date'
    case 'FLOAT':
    case 'DOUBLE':
      return 'number'
    case 'BYTE_ARRAY':
    case 'FIXED_LEN_BYTE_ARRAY':
      return 'Uint8Array'
    default:
      return 'unknown'
  }
}

function isAnnotatedList(node: SchemaTree): boolean {
  const convertedType = node.element.converted_type
  const logicalType = node.element.logical_type?.type
  return convertedType === 'LIST' || logicalType === 'LIST'
}

function isAnnotatedMap(node: SchemaTree): boolean {
  const convertedType = node.element.converted_type
  const logicalType = node.element.logical_type?.type
  return convertedType === 'MAP' || logicalType === 'MAP'
}

function mapKeyType(node: SchemaTree): string {
  const keyBaseType = primitiveType(node.element)
  if (keyBaseType === 'number' || keyBaseType === 'string' || keyBaseType === 'symbol') {
    return keyBaseType
  }
  return 'string'
}

function formatPropertyName(name: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    return name
  }
  return JSON.stringify(name)
}

function indentMultiline(value: string, indent: string): string {
  const lines = value.split('\n')
  if (lines.length <= 1) {
    return value
  }
  return lines
    .map((line, index) => (index === 0 ? line : `${indent}${line}`))
    .join('\n')
}

main()
