import { asyncBufferFromUrl, parquetReadObjects } from "hyparquet";

// This file was auto-generated by scripts/generate-parquet-schema.mts
// Source parquet file: transcripts/eval--llama-3-262k-2025-07-31-debater_sft-only--gpt-4-turbo-2024-04-09-judge_untrained--quality/full_debate_analysis.parquet
export interface FullDebateAnalysisRow {
  emptiness: {
    empty_speech_counts: Record<string, bigint>;
    debater_a_empty_files: string[];
    debater_b_empty_files: string[];
    unique_empty_files: string[];
    total_debates: bigint;
  };
  lengths: {
    debater_a_lengths: bigint[];
    debater_b_lengths: bigint[];
    transcript_count: bigint;
  };
  distribution: {
    identifier_counts: Record<string, bigint>;
    title_counts: Record<string, bigint>;
    transcript_count: bigint;
  };
  stats: {
    total_debates: bigint;
    debater_a_wins: bigint;
    debater_b_wins: bigint;
    judge_correct: bigint;
    first_debater_correct: bigint;
    debater_a_probs: number[];
    debater_b_probs: number[];
  };
}

export type FullDebateAnalysisRowFetchOptions = Omit<Parameters<typeof asyncBufferFromUrl>[0], 'url'>;

export async function fetchFullDebateAnalysisRows(url: string, options?: FullDebateAnalysisRowFetchOptions): Promise<FullDebateAnalysisRow[]> {
  const file = await asyncBufferFromUrl({ url, ...(options ?? {}) });
  const rows = await parquetReadObjects({ file, rowFormat: 'object' });
  return rows as FullDebateAnalysisRow[];
}
