import { parquetReadObjects } from "hyparquet";

// This file was auto-generated by scripts/generate-parquet-schema.mts
// Source parquet file: transcripts/eval--llama-3-262k-2025-07-31-debater_sft-only--gpt-4-turbo-2024-04-09-judge_untrained--quality/full_debate_analysis.parquet
export interface FullDebateAnalysisRow {
  emptiness: {
    empty_speech_counts: Record<string, bigint>;
    debater_a_empty_files: string[];
    debater_b_empty_files: string[];
    unique_empty_files: string[];
    total_debates: bigint;
  };
  lengths: {
    debater_a_lengths: bigint[];
    debater_b_lengths: bigint[];
    transcript_count: bigint;
  };
  distribution: {
    identifier_counts: Record<string, bigint>;
    title_counts: Record<string, bigint>;
    transcript_count: bigint;
  };
  stats: {
    total_debates: bigint;
    debater_a_wins: bigint;
    debater_b_wins: bigint;
    judge_correct: bigint;
    first_debater_correct: bigint;
    debater_a_probs: number[];
    debater_b_probs: number[];
  };
  configuration: {
    config_type: string;
    task_type: string;
    debater_name: string;
    debater_training_round: string;
    debater_is_reasoning: boolean;
    debater_model_type: string;
    debater_max_new_tokens: bigint;
    judge_name: string;
    judge_training_round: string;
    judge_model_type: string;
    judge_max_new_tokens: bigint;
  };
}


export interface FullDebateAnalysisRowFetchOptions {
  /** Custom fetch implementation (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Additional RequestInit options passed to fetch. */
  requestInit?: RequestInit;
}

export async function fetchFullDebateAnalysisRows(url: string, options?: FullDebateAnalysisRowFetchOptions): Promise<FullDebateAnalysisRow[]> {
  const logPrefix = '[fetchFullDebateAnalysisRows]';
  const fetchImpl = options?.fetch ?? globalThis.fetch;
  if (!fetchImpl) {
    throw new Error('fetch is not available in this environment');
  }
  const requestInit = options?.requestInit;
  console.info(logPrefix, 'downloading full parquet file to avoid truncated range responses', { url });
  const response = await fetchImpl(url, requestInit);
  if (!response.ok) {
    console.error(logPrefix, 'full download failed', { url, status: response.status });
    throw new Error(`parquet fetch failed ${response.status}`);
  }
  const buffer = await response.arrayBuffer();
  console.debug(logPrefix, 'download complete', { url, status: response.status, byteLength: buffer.byteLength });
  console.info(logPrefix, 'GitHub Pages only serves ~48KB for range requests; parsing from the full buffer instead.');
  const file = {
    byteLength: buffer.byteLength,
    async slice(start: number, end?: number) {
      return buffer.slice(start, end);
    },
  };
  try {
    const rows = await parquetReadObjects({
      file,
      rowFormat: 'object',
    } as Parameters<typeof parquetReadObjects>[0]);
    console.info(logPrefix, 'loaded parquet', { url, rowCount: rows.length });
    return rows as FullDebateAnalysisRow[];
  } catch (error) {
    console.error(logPrefix, 'parquet parsing failed even after full download', { url, error });
    throw error;
  }
}

