name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Change to your default branch if different
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11  # or python:3.11, python:3.11-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      # No need for setup-python when using container

      - name: Install dependencies
        run: |
          # Install Python dependencies
          pip install --upgrade pip
          # Install other dependencies if you have a requirements.txt
          pip install -r requirements.txt

      - name: Run inspect view bundle
        run: |
          # Run your inspect command with docs as output directory
          inspect view bundle --log-dir transcripts/inspect_logs --output-dir docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the docs directory generated by inspect-ai
          path: './docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
